#!/bin/bash

if [ -z "$PYFILE" ]; then
	echo "Error: \$PYFILE environment variable is not set."
	exit 1
fi

if [ ! -f "$PYFILE" ]; then
	echo "Error: File not found - $PYFILE"
	exit 1

fi

#Ru the Python script
python3 "$PYFILE"
